apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-watch-fruits
data:
  fruits: orange,apple,banana
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-watch-fruits-scripts
data:
  handler: |
    #!/bin/sh

    case "$1" in
        handle) echo "Channel: $2"
                echo "Current fruits: $3"
                echo "Previous fruits: $4"
        ;;
    esac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-watch-fruits
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-watch-fruits
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["kube-watch-fruits"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: kube-watch-fruits
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-watch-fruits
subjects:
- kind: ServiceAccount
  name: kube-watch-fruits
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-watch-fruits
spec:
  template:
    metadata:
      labels:
        app: kube-watch-fruits
    spec:
      containers:
      - name: kube-watch-fruits
        image: quay.io/aialferov/kube-watch:latest
        imagePullPolicy: Always
        args:
        - object
        - configmap
        - kube-watch-fruits
        - --jsonpath={.data.fruits}
        volumeMounts:
        - name: kubectl
          mountPath: /bin/kubectl
        - name: handler
          mountPath: /usr/share/kube-watch
      volumes:
      - name: kubectl
        hostPath:
          path: /opt/bin/kubectl
      - name: handler
        configMap:
          name: kube-watch-fruits-scripts
          defaultMode: 0744
      serviceAccount: kube-watch-fruits
      serviceAccountName: kube-watch-fruits
