apiVersion: v1
kind: Pod
metadata:
  name: a1
  namespace: n1
  labels:
    app: a1
    purpose: a
spec:
  containers:
  - image: gcr.io/google-containers/pause
    name: pause
---
apiVersion: v1
kind: Pod
metadata:
  name: b1
  namespace: n1
  labels:
    app: b1
    purpose: b
spec:
  containers:
  - image: gcr.io/google-containers/pause
    name: pause
---
apiVersion: v1
kind: Pod
metadata:
  name: a2
  namespace: n2
  labels:
    app: a2
    purpose: a
spec:
  containers:
  - image: gcr.io/google-containers/pause
    name: pause
---
apiVersion: v1
kind: Pod
metadata:
  name: b2
  namespace: n2
  labels:
    app: b2
    purpose: b
spec:
  containers:
  - image: gcr.io/google-containers/pause
    name: pause
